apiVersion: apps/v1
kind: Deployment
metadata:
  name: chart-inspector
  namespace: demo-system
  labels:
    app: chart-inspector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chart-inspector
  template:
    metadata:
      labels:
        app: chart-inspector
    spec:
      serviceAccountName: chart-inspector-sa
      containers:
      - name: chart-inspector-container
        image: kind.local/chart-inspector:latest
        args:
          - "-debug"
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: chart-inspector-service
spec:
  selector:
    app: chart-inspector
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081