apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chart-inspector-viewer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chart-inspector-viewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chart-inspector-viewer
subjects:
- kind: ServiceAccount
  name: chart-inspector-sa
  namespace: demo-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chart-inspector-sa
  namespace: demo-system