// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/resources": {
            "get": {
                "description": "Get Helm chart resources",
                "produces": [
                    "application/json"
                ],
                "summary": "Get Helm chart resources",
                "operationId": "get-chart-resources",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Composition name",
                        "name": "compositionUID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Composition namespace",
                        "name": "compositionNamespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Composition definition name",
                        "name": "compositionDefinitionUID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Composition definition namespace",
                        "name": "compositionDefinitionNamespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/resources.Resource"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "resources.Resource": {
            "type": "object",
            "properties": {
                "group": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Chart Inspector API",
	Description:      "This is the API for the Chart Inspector service. It provides endpoints for inspecting Helm charts.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
