basePath: /
definitions:
  resources.Resource:
    properties:
      group:
        type: string
      name:
        type: string
      namespace:
        type: string
      resource:
        type: string
      version:
        type: string
    type: object
info:
  contact: {}
  description: This is the API for the Chart Inspector service. It provides endpoints
    for inspecting Helm charts.
  title: Chart Inspector API
  version: "1.0"
paths:
  /resources:
    get:
      description: Get Helm chart resources
      operationId: get-chart-resources
      parameters:
      - description: Composition name
        in: query
        name: compositionUID
        required: true
        type: string
      - description: Composition namespace
        in: query
        name: compositionNamespace
        required: true
        type: string
      - description: Composition definition name
        in: query
        name: compositionDefinitionUID
        required: true
        type: string
      - description: Composition definition namespace
        in: query
        name: compositionDefinitionNamespace
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/resources.Resource'
            type: array
      summary: Get Helm chart resources
swagger: "2.0"
